### PR TITLE
Fix URL to www.RiskProfiler.ca

### PR DESCRIPTION
**Pull request by anthonyfok**
Thanks!  :-)

### CODE REVIEW

**Review by tieganh — APPROVED** [review]

**Comment by tieganh** [comment]
Approved but will leave it to you to merge. @anthonyfok

**Comment by anthonyfok** [comment]
In lieu of requesting another review after resolving the merge request, I am going to simply merge the changes and push it directly to `master`.  Hope it works!

**Comment by anthonyfok** [comment]
Nope, it did not work:

```
remote: Resolving deltas: 100% (7/7), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:OpenDRR/seismic-risk-model.git
 ! [remote rejected] master -> master (protected branch hook declined)
```

(I probably shouldn't try to sneak around GitHub's protection, haha!)

Thanks again @tieganh, I'll need your help reviewing this again.  Many thanks!

**Review by tieganh — APPROVED** [review]

**Comment by tieganh** [comment]
Reviewed but will leave it to you to merge :)

**Pull request merged**
