### PR TITLE
Minor fixes for README.md / LISEZMOI.md and French GitHub Pages

### PR DESCRIPTION
**Pull request by anthonyfok**
Hey @tieganh,

Here are two minor fixes for French:

1. Fix some punctuations in French GitHub Pages:
    - Add missing hyphens in names of some provinces and territories
    - Add missing _Accent aigu_ for Québec
    - Use of _espace insécable_ (non-breaking space)
    - Use of guillemets instead of English quotation marks, etc.

2. Add English/Français language links on top of README.md and LISEZMOI.md

Many thanks!

### CODE REVIEW

**Comment by drotheram** [comment]
@tieganh would you kindly review and approve/deny at your convenience

**Comment by drotheram** [comment]
@tieganh  kindly review and approve/reject when able

**Review by tieganh — APPROVED** [review]

**Comment by tieganh** [comment]
Awesome work. Approved - will leave it to you folks to merge when ready! @drotheram @anthonyfok

**Comment by anthonyfok** [comment]
Awesome!  Thank you so much @tieganh!

**Pull request merged**
